<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GCHE5QNO" failures="6" tests="6" name="TestNG tests" time="0.077" errors="0" timestamp="13 Apr 2025 12:37:03 GMT">
  <testcase classname="Assignment_1.LoginNGTest" name="testCheckLocalPhoneNumber" time="0.001">
    <failure type="java.lang.StringIndexOutOfBoundsException" message="Range [0, 3) out of bounds for length 0">
      <![CDATA[java.lang.StringIndexOutOfBoundsException: Range [0, 3) out of bounds for length 0
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4963)
at java.base/java.lang.String.substring(String.java:2925)
at Assignment_1.Login.checkLocalPhoneNumber(Login.java:47)
at Assignment_1.LoginNGTest.testCheckLocalPhoneNumber(LoginNGTest.java:78)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testCheckLocalPhoneNumber -->
  <testcase classname="Assignment_1.LoginNGTest" name="testCheckPasswordComplexity" time="0.001">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at Assignment_1.LoginNGTest.testCheckPasswordComplexity(LoginNGTest.java:66)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testCheckPasswordComplexity -->
  <testcase classname="Assignment_1.LoginNGTest" name="testCheckUsername" time="0.0">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at Assignment_1.LoginNGTest.testCheckUsername(LoginNGTest.java:51)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testCheckUsername -->
  <testcase classname="Assignment_1.LoginNGTest" name="testLoginUser" time="0.029">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at Assignment_1.LoginNGTest.testLoginUser(LoginNGTest.java:114)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testLoginUser -->
  <testcase classname="Assignment_1.LoginNGTest" name="testRegisterUser" time="0.001">
    <failure type="java.lang.UnsupportedOperationException" message="Not supported yet.">
      <![CDATA[java.lang.UnsupportedOperationException: Not supported yet.
at Assignment_1.Login.checkPhoneNumber(Login.java:88)
at Assignment_1.Login.registerUser(Login.java:57)
at Assignment_1.LoginNGTest.testRegisterUser(LoginNGTest.java:95)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRegisterUser -->
  <testcase classname="Assignment_1.LoginNGTest" name="testReturnLoginStatus" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [] but found [A failed login]">
      <![CDATA[java.lang.AssertionError: expected [] but found [A failed login]
at Assignment_1.LoginNGTest.testReturnLoginStatus(LoginNGTest.java:128)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testReturnLoginStatus -->
</testsuite> <!-- TestNG tests -->
